// native-integration/capacitor/angular/src/app/home/home.component.ts
// Home page — choose a login mode, then navigate to the Embed route (named routes, real history).
// Mirrors the react-native-expo HomeScreen (Home → Embed) and the web-integration manual/auto pages.
import { NgClass } from '@angular/common';
import { Component, NgZone, type OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { getEmbedToken } from '../../mint';

type State = 'idle' | 'loading' | 'error';
const IDLE = 'Choose a login mode to open the embed.';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [NgClass],
  template: `
    <div class="aiq-app">
      <header class="aiq-hero">
        <div class="aiq-badge">✨</div>
        <h1 class="aiq-hero-title">Applaud IQ</h1>
        <p class="aiq-hero-sub">Capacitor · angular — embed example</p>
      </header>
      <main class="aiq-content">
        <p class="aiq-section-label">Choose a login mode</p>
        <button
          class="aiq-card"
          [ngClass]="{ 'is-busy': busy === 'manual', 'is-dim': busy && busy !== 'manual' }"
          [disabled]="busy !== null"
          (click)="openManual()"
        >
          <span class="aiq-tile">🔒</span>
          <span class="aiq-card-text">
            <div class="aiq-card-title">Manual login</div>
            <div class="aiq-card-sub">Employees sign in inside the embed (email + SSO). No server needed.</div>
          </span>
          <span class="aiq-chevron">›</span><span class="aiq-spinner"></span>
        </button>
        <button
          class="aiq-card"
          [ngClass]="{ 'is-busy': busy === 'auto', 'is-dim': busy && busy !== 'auto' }"
          [disabled]="busy !== null"
          (click)="openAuto()"
        >
          <span class="aiq-tile">⚡</span>
          <span class="aiq-card-text">
            <div class="aiq-card-title">Auto-login</div>
            <div class="aiq-card-sub">Silent sign-in with a one-time token minted on your server.</div>
          </span>
          <span class="aiq-chevron">›</span><span class="aiq-spinner"></span>
        </button>
        <div class="aiq-status" [ngClass]="'is-' + state">
          <span class="aiq-status-icon">{{ icon[state] }}</span>
          <span class="aiq-status-text">{{ text }}</span>
        </div>
        <p class="aiq-footer">&#64;applaudiq/embed-capacitor · by Arulraj V</p>
      </main>
    </div>
  `,
})
export class HomeComponent implements OnInit {
  state: State = 'idle';
  text = IDLE;
  busy: 'manual' | 'auto' | null = null;
  icon: Record<State, string> = { idle: 'ℹ', loading: '↻', error: '⚠' };

  constructor(
    private router: Router,
    private zone: NgZone,
  ) {}

  ngOnInit(): void {
    // Web (non-native) same-page SSO return: the gateway redirected back here with `#aiq_sso=<code>`.
    // Resume by opening the embed route in manual mode — the SDK reads the code and completes sign-in.
    // No-op on native (the deep link drives that flow) and when there's no SSO return.
    if (typeof window !== 'undefined' && window.location.hash.includes('aiq_sso')) {
      void this.router.navigate(['/embed'], { queryParams: { mode: 'manual' } });
    }
  }

  openManual(): void {
    void this.router.navigate(['/embed'], { queryParams: { mode: 'manual' } });
  }

  async openAuto(): Promise<void> {
    this.busy = 'auto';
    this.state = 'loading';
    this.text = 'Minting a one-time token…';
    let token: string | undefined;
    try {
      token = await getEmbedToken();
    } catch {
      token = undefined;
    }
    // Pass the minted token via router state (never a query param — tokens stay out of URLs).
    this.zone.run(() => {
      this.busy = null;
      this.state = 'idle';
      this.text = IDLE;
      void this.router.navigate(['/embed'], { queryParams: { mode: 'auto' }, state: { token } });
    });
  }
}

// native-integration/capacitor/react/src/pages/Home.tsx
// Home page — choose a login mode, then navigate to the Embed route (named routes, real history).
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { getEmbedToken } from '../mint';

type State = 'idle' | 'loading' | 'error';
const ICON: Record<State, string> = { idle: 'ℹ', loading: '↻', error: '⚠' };
const IDLE = 'Choose a login mode to open the embed.';

export default function Home() {
  const navigate = useNavigate();
  const [state, setState] = useState<State>('idle');
  const [text, setText] = useState(IDLE);
  const [busy, setBusy] = useState<'manual' | 'auto' | null>(null);

  useEffect(() => {
    // Web (non-native) same-page SSO return: the gateway redirected back here with `#aiq_sso=<code>`.
    // Resume by opening the embed route in manual mode — the SDK reads the code and completes sign-in.
    if (typeof window !== 'undefined' && window.location.hash.includes('aiq_sso')) {
      navigate('/embed?mode=manual');
    }
  }, [navigate]);

  const openManual = () => navigate('/embed?mode=manual');

  const openAuto = async () => {
    setBusy('auto');
    setState('loading');
    setText('Minting a one-time token…');
    let token: string | undefined;
    try {
      token = await getEmbedToken();
    } catch {
      token = undefined;
    }
    // Pass the minted token via router state (never a query param — tokens stay out of URLs).
    setBusy(null);
    setState('idle');
    setText(IDLE);
    navigate('/embed?mode=auto', { state: { token } });
  };

  const card = (
    id: 'manual' | 'auto',
    icon: string,
    title: string,
    sub: string,
    onClick: () => void,
  ) => (
    <button
      className={`aiq-card ${busy === id ? 'is-busy' : ''} ${busy && busy !== id ? 'is-dim' : ''}`}
      disabled={busy !== null}
      onClick={onClick}
    >
      <span className="aiq-tile">{icon}</span>
      <span className="aiq-card-text">
        <div className="aiq-card-title">{title}</div>
        <div className="aiq-card-sub">{sub}</div>
      </span>
      <span className="aiq-chevron">›</span>
      <span className="aiq-spinner" />
    </button>
  );

  return (
    <div className="aiq-app">
      <header className="aiq-hero">
        <div className="aiq-badge">✨</div>
        <h1 className="aiq-hero-title">Applaud IQ</h1>
        <p className="aiq-hero-sub">Capacitor · react — embed example</p>
      </header>
      <main className="aiq-content">
        <p className="aiq-section-label">Choose a login mode</p>
        {card(
          'manual',
          '🔒',
          'Manual login',
          'Employees sign in inside the embed (email + SSO). No server needed.',
          openManual,
        )}
        {card(
          'auto',
          '⚡',
          'Auto-login',
          'Silent sign-in with a one-time token minted on your server.',
          openAuto,
        )}
        <div className={`aiq-status is-${state}`}>
          <span className="aiq-status-icon">{ICON[state]}</span>
          <span className="aiq-status-text">{text}</span>
        </div>
        <p className="aiq-footer">@applaudiq/embed-capacitor · by Arulraj V</p>
      </main>
    </div>
  );
}
