// web-integration/svelte/src/App.svelte
<script lang="ts">
  import { Route, Router } from 'svelte-routing';

  import Nav from './lib/Nav.svelte';
  import AutoLogin from './routes/AutoLogin.svelte';
  import Home from './routes/Home.svelte';
  import ManualLogin from './routes/ManualLogin.svelte';
</script>

<Router>
  <div class="aiq-app">
    <Nav />
    <main class="aiq-main">
      <Route path="/auto" component={AutoLogin} />
      <Route path="/manual" component={ManualLogin} />
      <Route path="/"><Home /></Route>
    </main>
  </div>
</Router>

// web-integration/react-vite/src/App.tsx
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';

import { Layout } from './components/Layout';
import { AutoLogin } from './routes/AutoLogin';
import { Home } from './routes/Home';
import { ManualLogin } from './routes/ManualLogin';

export function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route element={<Layout />}>
          <Route path="/" element={<Home />} />
          <Route path="/auto" element={<AutoLogin />} />
          <Route path="/manual" element={<ManualLogin />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}
