// native-integration/capacitor/angular/src/app/app.component.ts
// App shell — just hosts the router outlet. Real pages live in home/ and embed/ (named routes).
// Shares the brand theme (theme.css, wired via angular.json styles) with the iOS / Android / Flutter examples.
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `<router-outlet></router-outlet>`,
})
export class AppComponent {}

// native-integration/capacitor/react/src/App.tsx
// App shell — just the router. Real pages live in pages/Home + pages/Embed (named routes).
// Plain React (no Ionic), so the SDK owns the only back affordance: iOS left-edge swipe + Android Back.
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';

import Embed from './pages/Embed';
import Home from './pages/Home';
import './theme.css';

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/embed" element={<Embed />} />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </BrowserRouter>
  );
}
