// web-integration/nextjs/app/components/Nav.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

/** App shell nav: sticky top bar with brand + links to each mode. */
export function Nav() {
  const pathname = usePathname();
  const cls = (href: string, exact = false) =>
    (exact ? pathname === href : pathname.startsWith(href)) ? 'active' : undefined;

  return (
    <nav className="aiq-nav">
      <span className="aiq-brand">
        ApplaudIQ <span className="dot">·</span> Next.js
      </span>
      <div className="aiq-links">
        <Link href="/" className={cls('/', true)}>
          Home
        </Link>
        <Link href="/auto" className={cls('/auto')}>
          Auto-login
        </Link>
        <Link href="/manual" className={cls('/manual')}>
          Manual login
        </Link>
      </div>
    </nav>
  );
}

// web-integration/svelte/src/lib/Nav.svelte
<script lang="ts">
  import { Link } from 'svelte-routing';

  // svelte-routing's <Link> exposes a getProps hook with the current match info.
  // Home (`/`) must match exactly; the mode pages match their own path.
  const exact = ({ isCurrent }: { isCurrent: boolean }) => (isCurrent ? { class: 'active' } : {});
  const partial = ({ isPartiallyCurrent, isCurrent }: { isPartiallyCurrent: boolean; isCurrent: boolean }) =>
    isPartiallyCurrent || isCurrent ? { class: 'active' } : {};
</script>

<!-- App shell: sticky top nav with active highlighting. -->
<nav class="aiq-nav">
  <span class="aiq-brand">
    ApplaudIQ <span class="dot">·</span> Svelte
  </span>
  <div class="aiq-links">
    <Link to="/" getProps={exact}>Home</Link>
    <Link to="/auto" getProps={partial}>Auto-login</Link>
    <Link to="/manual" getProps={partial}>Manual login</Link>
  </div>
</nav>
