// web-integration/svelte/src/components/EmbedLoading.svelte
<script lang="ts">
  // The transient "minting a token…" state shown before the auto-login embed mounts.
  export let title: string;
  export let what: string;
</script>

<section class="aiq-mode">
  <div class="aiq-subhead">
    <h2>{title}</h2>
    <span class="what">{what}</span>
    <span class="pill pill-right">opening…</span>
  </div>
  <div class="aiq-embed"></div>
</section>

// web-integration/react-vite/src/components/EmbedLoading.tsx
/** The transient "minting a token…" state shown before the auto-login embed mounts. */
export function EmbedLoading({ title, what }: { title: string; what: string }) {
  return (
    <section className="aiq-mode">
      <div className="aiq-subhead">
        <h2>{title}</h2>
        <span className="what">{what}</span>
        <span className="pill pill-right">opening…</span>
      </div>
      <div className="aiq-embed" />
    </section>
  );
}
