// web-integration/svelte/src/components/EmbedView.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';

  import { openEmbed } from '../lib/openEmbed';
  import type { ApplaudIQHandle, ApplaudIQLoginMode } from '../applaudiq.d';

  export let title: string;
  export let what: string;
  export let mode: ApplaudIQLoginMode;
  export let token: string | undefined = undefined;
  export let getToken: (() => Promise<string>) | undefined = undefined;

  const CONTAINER = 'applaudiq-recognition';

  type Kind = 'ready' | 'pending' | 'error' | '';
  let status = 'opening…';
  let kind: Kind = '';

  let handle: ApplaudIQHandle | undefined;

  onMount(() => {
    handle = openEmbed(`#${CONTAINER}`, {
      mode,
      token,
      getToken,
      onReady: () => ((status = 'signed in'), (kind = 'ready')),
      onAuthPending: () => ((status = 'waiting for HR approval'), (kind = 'pending')),
      onError: (e) => ((status = e.message), (kind = 'error')),
    });
  });

  onDestroy(() => handle?.close());
</script>

<!-- Sub-header (title + status pill) and the inline container the SDK mounts into. -->
<section class="aiq-mode">
  <div class="aiq-subhead">
    <h2>{title}</h2>
    <span class="what">{what}</span>
    <span class="pill pill-right {kind}">{status}</span>
  </div>
  {#if kind === 'pending'}
    <div class="aiq-banner pending">
      ⏳ Waiting for HR approval — you'll get access once an admin approves you.
    </div>
  {/if}
  <div id={CONTAINER} class="aiq-embed"></div>
</section>

// web-integration/react-vite/src/components/EmbedView.tsx
import { useState } from 'react';

import { useApplaudIQ } from '../useApplaudIQ';

const CONTAINER = 'applaudiq-recognition';

type Status = { text: string; kind?: 'ready' | 'pending' | 'error' };

/**
 * Renders the embed for a single login mode: a sub-header (title + status pill)
 * and the inline container the SDK mounts the portal into.
 */
export function EmbedView({
  title,
  what,
  mode,
  token,
  getToken,
}: {
  title: string;
  what: string;
  mode: 'auto' | 'manual';
  token?: string;
  getToken?: () => Promise<string>;
}) {
  const [status, setStatus] = useState<Status>({ text: 'opening…' });

  useApplaudIQ(CONTAINER, {
    mode,
    token,
    getToken,
    onReady: () => setStatus({ text: 'signed in', kind: 'ready' }),
    onAuthPending: () => setStatus({ text: 'waiting for HR approval', kind: 'pending' }),
    onError: (e) => setStatus({ text: e.message, kind: 'error' }),
  });

  return (
    <section className="aiq-mode">
      <div className="aiq-subhead">
        <h2>{title}</h2>
        <span className="what">{what}</span>
        <span className={'pill pill-right' + (status.kind ? ' ' + status.kind : '')}>{status.text}</span>
      </div>
      {status.kind === 'pending' && (
        <div className="aiq-banner pending">
          ⏳ Waiting for HR approval — you'll get access once an admin approves you.
        </div>
      )}
      <div id={CONTAINER} className="aiq-embed" />
    </section>
  );
}
