// web-integration/vue/src/components/NeedsServerNotice.vue
<script setup lang="ts">
// Shown when auto-login can't mint a token because no backend is wired yet.
</script>

<template>
  <div class="aiq-callout">
    <h3>Auto-login needs a server</h3>
    <p>
      Wire <code>getEmbedToken()</code> in <code>src/useEmbedToken.ts</code> to your
      <code> /api/mint</code> endpoint — it exchanges your <code>aiq_embed_…</code> secret for a one-time
      token. See <strong>MINTING.md</strong>. Or try <strong>Manual login</strong> — it needs no server.
    </p>
  </div>
</template>

// web-integration/angular/src/app/needs-server-notice.component.ts
import { Component } from '@angular/core';

/** Shown when auto-login can't mint a token because no backend is wired yet. */
@Component({
  selector: 'app-needs-server-notice',
  standalone: true,
  template: `
    <div class="aiq-callout">
      <h3>Auto-login needs a server</h3>
      <p>
        Wire <code>getEmbedToken()</code> in <code>src/app/embed-token.service.ts</code> to your
        <code> /api/mint</code> endpoint — it exchanges your <code>aiq_embed_…</code> secret for a one-time
        token. See <strong>MINTING.md</strong>. Or try <strong>Manual login</strong> — it needs no server.
      </p>
    </div>
  `,
})
export class NeedsServerNoticeComponent {}
