// web-integration/react-vite/src/routes/ManualLogin.tsx
import { EmbedView } from '../components/EmbedView';

/** Manual login route — publishable key only; the embed shows the portal's own login. */
export function ManualLogin() {
  return (
    <EmbedView
      title="Manual login"
      what="The embed shows Applaud IQ's own login (email / SSO). No server, no token."
      mode="manual"
    />
  );
}

// web-integration/svelte/src/routes/ManualLogin.svelte
<script lang="ts">
  import EmbedView from '../components/EmbedView.svelte';
</script>

<!-- Manual login route — publishable key only; the embed shows the portal's own login. -->
<EmbedView
  title="Manual login"
  what="The embed shows Applaud IQ's own login (email / SSO). No server, no token."
  mode="manual"
/>
